version: '3'
services:

  match-platform-gateway:
    container_name: match-platform-gateway #配置容器名
    build:
      context: ./chaos-match-platform-gateway
      dockerfile: Dockerfile #指定dockerFile文件
    image: java/match-platform-gateway # 指定镜像名
    ports:
      - "10010:10010" # 暴露端口
    volumes:
      - ./logs:/logs # 创建容器数据卷
    networks:
      - KQM

  match-platform-auth:
    container_name: match-platform-auth #配置容器名
    build:
      context: ./chaos-match-platform-auth
      dockerfile: Dockerfile #指定dockerFile文件
    image: java/match-platform-auth # 指定镜像名
    ports:
      - "8071:8071" # 暴露端口
    volumes:
      - ./logs:/logs # 创建容器数据卷
    networks:
      - KQM

  match-platform-weixin:
    container_name: match-platform-weixin #配置容器名
    build:
      context: ./chaos-match-platform-weixin
      dockerfile: Dockerfile #指定dockerFile文件
    image: java/match-platform-weixin # 指定镜像名
    ports:
      - "8072:8072" # 暴露端口
    volumes:
      - ./logs:/logs # 创建容器数据卷
    networks:
      - KQM

  match-platform-user:
    container_name: match-platform-user #配置容器名
    build:
      context: ./chaos-match-platform-user
      dockerfile: Dockerfile #指定dockerFile文件
    image: java/match-platform-user # 指定镜像名
    ports:
      - "8073:8073" # 暴露端口
    volumes:
      - ./logs:/logs # 创建容器数据卷
    networks:
      - KQM

  match-platform-chat:
    container_name: match-platform-chat #配置容器名
    build:
      context: ./chaos-match-platform-chat
      dockerfile: Dockerfile #指定dockerFile文件
    image: java/match-platform-chat # 指定镜像名
    ports:
      - "8074:8074" # 暴露端口
    volumes:
      - ./logs:/logs # 创建容器数据卷
    networks:
      - KQM

  match-platform-post:
    container_name: match-platform-post #配置容器名
    build:
      context: ./chaos-match-platform-post
      dockerfile: Dockerfile #指定dockerFile文件
    image: java/match-platform-post # 指定镜像名
    ports:
      - "8075:8075" # 暴露端口
    volumes:
      - ./logs:/logs # 创建容器数据卷
    networks:
      - KQM

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: unless-stopped
    ports:
      - 4080:4080
    volumes:
      - ./data:/data
    environment:
      - ZINC_DATA_PATH="/data"
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123

networks:
  KQM: