# 基础镜像
FROM getmeili/meilisearch:v1.6
# author
MAINTAINER XSINXCOS

EXPOSE 7700
# 挂载目录
VOLUME /home/order/meilisearch
# 创建目录
RUN mkdir -p /home/order/meilisearch
# 指定路径
WORKDIR /home/order/meilisearch

